// Shape of config.js, generated by make-config.ps1 from the repo's .env and git-ignored.
var CONFIG = {
  supabaseUrl: 'https://your-project-ref.supabase.co',
  supabasePublishableKey: 'sb_publishable_your-key'
};
